dist: trusty
language: ruby
cache: npm
services:
  - docker

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin

git:
  depth: 10

notifications:
  email:
    on_success: never
    on_failure: change

jobs:
  include:
    - stage: test
      script: nvm install 12.1 && npm i nyc@15.0.0 -g
    - script: just test
    - script: just run-test-d
    - script: just build-test

    - stage: image build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - just build-c

    - stage: push new image
      script: just push && just push-latest
      if: branch = master
