dist: trusty
language: node_js
cache: npm

services:
  - docker

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin

git:
  depth: 10

notifications:
  email:
    on_success: never
    on_failure: change

jobs:
  include:
    - stage: tests
      install: nvm install 12.1 && npm i nyc@15.0.0 -g && npm i --save-dev
      script: just test && just run-test-d

    - stage: image build
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - just build-c

    - stage: coveralls
      install: nvm install 12.1 && npm i nyc@15.0.0 -g && npm i --save-dev
      script: npm run coveralls
      if: branch = master AND type = push

    - stage: push new image
      script: just build-nc && just push && just push-latest
      if: branch = master AND type = push
