version: '3'

services:
  tendermint-prometheus-exporter:
    container_name: tendermint-prometheus-exporter
    image: dmi7ry/tendermint-prometheus-exporter:latest
    environment:
      - LOG_LEVEL=info
    ports:
      - "9675:9675"
    # cosmos validator info + status not supported yet
    command: >
      serve
      --port 9675
      --timeout 5000
      --target https://api.minter.one --status --net-info --candidates --
      --target http://api-01.minter.store:8841 --status --net-info --candidates --
      --target http://cosmos-node.sparkpool.com:26657 --net-info
