# my global config
global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:

  - job_name: 'minter-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['minter_exporter:9675']

  - job_name: 'minter-node'
    scrape_interval: 30s
    static_configs:
      - targets: ['minter_node:26660']
