{
 "title": "Minter Dashboard",
 "description": "Dashboard based on tendermint-exporter",
 "tags": [
  "minter",
  "minter-api",
  "minter-node"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "api",
    "query": "label_values(minter_status_latest_block_time, target)"
   },
   {
    "name": "node",
    "query": "label_values(grpc_server_handled_total,instance)"
   }
  ]
 },
 "panels": [
  { "title": "NODE $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "API response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api{instance=\"$node\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$node\"}[1m])",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$node\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"$node\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "GO memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$node\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$node\"}[1m])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "Goroutines & file descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$node\"}",
     "legendFormat": "goroutines"
    },
    {
     "expr": "process_open_fds{instance=\"$node\"}",
     "legendFormat": "open file descriptors"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"$node\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "API summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Peers Connected Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(minter_net_info_peers_connected_total{target=~\"$api\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(minter_status_latest_block_height{target=~\"$api\"}) by (target, moniker)",
     "legendFormat": "latest block {{target}}({{moniker}})"
    },
    {
     "expr": "avg(delta(minter_status_latest_block_height{target=~\"$api\"}[10m])) by (target, moniker)",
     "legendFormat": "blocks/10min {{target}}({{moniker}})"
    }
   ]
  },
  {
   "title": "Candidates Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Candidates Stake",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "sci" }
     ],
     "targets": [
      {
       "expr": "sort_desc(avg(minter_candidates_info_stake) by (owner_address)/100000000) != 0",
       "legendFormat": "{{owner_address}}"
      }
     ]
    },
    {
     "title": "Candidates Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(minter_candidates_info_status) by (owner_address)",
       "legendFormat": "{{owner_address}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API $api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "api",
   "collapsed": true,
   "panels": [
    {
     "title": "Latest Block - $api",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "avg(minter_status_latest_block_height{target=~\"$api\"}) by (target, moniker)",
       "legendFormat": "latest block ({{moniker}})"
      },
      {
       "expr": "delta(minter_status_latest_block_height{target=~\"$api\"}[10m])",
       "legendFormat": "blocks/10m ({{moniker}})"
      }
     ]
    },
    {
     "title": "Peers Connected - $api",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(minter_net_info_peers_connected_total{target=~\"$api\"}) by (target)",
       "legendFormat": "peers connected"
      }
     ]
    },
    {
     "title": "Network",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 42 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(minter_status_tm_status_node_info_network{target=~\"$api\"}) by (network)"
      }
     ]
    },
    {
     "title": "Latest Block Time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 7, "x": 17, "y": 45 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "minter_status_latest_block_time{target=~\"$api\"}"
      }
     ]
    },
    {
     "title": "Latest Block Height",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 17, "y": 48 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "minter_status_latest_block_height{target=~\"$api\"}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 48 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(minter_status_node_version{target=~\"$api\"}) by (version)"
      }
     ]
    },
    {
     "title": "Node in (by peer) - $api",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(minter_net_info_peer_info_connect_received_bytes_total{target=~\"$api\"}[1m])) by (moniker, listen_addr)",
       "legendFormat": "{{listen_addr}} ({{moniker}})"
      }
     ]
    },
    {
     "title": "Node out (by peer) - $api",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(minter_net_info_peer_info_connect_sent_bytes_total{target=~\"$api\"}[1m])) by (moniker, listen_addr)",
       "legendFormat": "{{listen_addr}} ({{moniker}})"
      }
     ]
    },
    {
     "title": "Node in/out - $api",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(minter_net_info_peer_info_connect_sent_bytes_total{target=~\"$api\"}[5m]))",
       "legendFormat": "out"
      },
      {
       "expr": "sum(rate(minter_net_info_peer_info_connect_received_bytes_total{target=~\"$api\"}[5m]))",
       "legendFormat": "in"
      }
     ]
    },
    {
     "title": "Connected Outbound Peers - $api",
     "type": "graph",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 66 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "minter_net_info_peer_info_connect_is_outbound{target=~\"$api\"} == 1",
       "legendFormat": "{{remote_ip}} ({{moniker}})"
      }
     ]
    }
   ]
  }
 ]
}