#!/usr/bin/env sh
set -ex
printenv

export APP_VERSION=$(grep 'version' package.json | sed 's/.*"version": "\(.*\)".*/\1/')

docker build \
	--build-arg EXPORTER_VERSION=$APP_VERSION \
	--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
	--build-arg VCS_REF=`git rev-parse --short HEAD` \
	-t $IMAGE_NAME .
