name: main workflow

on:
  push:
    paths:
      - 'src/**'
      - 'Justfile'
      - '.github/workflows/main.yml'
      - 'Dockerfile'
      - '.dockerignore'

  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Justfile'
      - '.github/workflows/main.yml'

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:

      - name: install just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin

      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.1'

      - name: install nyc & deps
        run: cd src && npm i nyc@15.0.0 -g && npm i --save-dev

      - name: run npm test
        run: just test

      - name: run smoke test
        run: just run-test-d

  coveralls:
    if: github.ref == 'refs/heads/master' || github.head_ref
    needs: [tests]
    runs-on: ubuntu-latest
    steps:

      - name: set envs
        run: |
          echo ::set-env name=CURRENT_BRANCH::$(echo ${GITHUB_REF#refs/heads/})

      - name: override branch for PR's
        run: |
          echo ::set-env name=CURRENT_BRANCH::$(echo ${GITHUB_SOURCE_REF})
        if: github.event_name == 'pull_request'

      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.1'

      - name: install nyc & deps
        run: cd src && npm i nyc@15.0.0 -g && npm i --save-dev

      - name: run npm coveralls
        run: cd src && npm run coveralls
        env:
          COVERALLS_SERVICE_NAME: GitHub Actions
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          COVERALLS_GIT_BRANCH: ${{ env.CURRENT_BRANCH }}

  sonar:
    if: github.ref == 'refs/heads/master' || github.head_ref
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src

  docker:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:

      - name: install just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin

      - name: checkout
        uses: actions/checkout@v2

      - name: docker login
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: docker build
        run: just build-nc

      - name: docker push version
        run: just push
        if: github.ref == 'refs/heads/master'

      - name: docker push latest
        run: just push-latest
        if: github.ref == 'refs/heads/master'
