name: docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 5

      - name: get version
        run: export VERSION=$(jq -r .version src/package.json)

      - name: build & push
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          IMAGE_NAME: "dmi7ry/tendermint-prometheus-exporter"
          # LATEST: "true"
          TAG_NAME: ${{ VERSION }}
