name: main workflow


on:
  push:
    paths:
      - 'src/**'
      - 'Justfile'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'Justfile'

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:

      - name: install just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin

      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.1'

      - name: install nyc & deps
        run: cd src && npm i nyc@15.0.0 -g && npm i --save-dev

      - name: run npm test
        run: just test

      - name: run smoke test
        run: just run-test-d

  coveralls:
    if: github.ref == 'refs/heads/master'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.1'

      - name: install nyc & deps
        run: cd src && npm i nyc@15.0.0 -g && npm i --save-dev

      - name: run npm coveralls
        run: cd src && npm run coveralls

  docker:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:

      - name: install just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin

      - name: checkout
        uses: actions/checkout@v2

      - name: docker login
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: docker build
        run: just build-nc

      - name: docker push version
        run: just push
        if: github.ref == 'refs/heads/master'

      - name: docker push latest
        run: just push-latest
        if: github.ref == 'refs/heads/master'
